config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :comments
    resources :users
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments
  resources :relationships, only: [:create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/search', to: 'articles#search', via: 'get'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user
	default_scope -> { order('updated_at DESC') }
	validates :user_id, presence: true
	validates :title, presence: true, length: { minimum: 5 }
	validates :text, presence: true, length: { minimum: 10 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def home
		if signed_in?
			@comment = current_user.comments.build
			#@feed_items = current_user.feed.paginate(page: params[:page])
		end
	end

	def index
		@title = "Список статей"
		@articles = Article.paginate :page => params[:page], :per_page => 15
		#@article = Article.new
		#@user = User.find_by(id: params[:user_id])
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	def search
		@articles = (Article.where("title LIKE '%"+params[:search]+"%' OR text LIKE '%"+params[:search]+"%'")).paginate :page => params[:page], :per_page => 15
		@title = "Результаты поиска по фразе '"+params[:search]+"'"
		render 'index'
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<ol class="comments">
	<li>
		<h3>  <%= article.title %>
			<i class="article_info">( Автор: <%= article.user.fio %> )</i>
		</h3> 
		<span class="content">
			<% if params[:action] == 'show' %>
				<%= article.text.html_safe %>
			<% else %>
				<%= truncate_html article.text, :length => 300  %> <%= link_to "Подробнее", article_path(article) %>
			<% end %>
		</span>
		<span class="timestamp">
			<% if article.created_at == article.updated_at %>
				Статья добавлена <%= time_ago_in_words(article.created_at) %> назад.
			<% else %>
				Статья обновлена <%= time_ago_in_words(article.updated_at) %> назад.
			<% end %>
		</span>
		<% if current_user?(article.user) %>
			<%= link_to "Редактировать", edit_article_path(article), class: "btn btn-large btn-primary" %>
			<p class="li_right"><%= link_to "Удалить", article, method: :delete,
				data: { confirm: "Вы уверены?" },
				title: article.text %>
			</p>
		<% end %>
	</li>
</ol>

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			Количество ошибок при сохранении статьи: <%= @article.errors.count %>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.cktext_area :text, rows: 10 %>
	</p>

	<p>
		<%= f.submit "Сохранить статью", class: "btn btn-large btn-primary" %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Редактирование статьи</h1>
<%= render 'form' %>

<%= link_to 'Назад', articles_path %>

app/views/articles/index.html.erb
<h1><%= @title %> (статей: <%= @articles.count %>) </h1>
<%= will_paginate %>
	
	<% @articles.each do |article| %>
		<%= render article %>
	<% end %>

<%= will_paginate %>

app/views/articles/new.html.erb
<h1>Новая статья</h1>
<%= render 'form' %>

<%= link_to 'Назад', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>
<ol class="comments">
	<li><%= link_to 'Назад', articles_path %></li>
</ol>

<h2>Комментарии</h2>
<%= render @article.comments %>

<% if signed_in? %>
	<h2>Добавить комментарий:</h2>
	<%= render 'comments/form' %>
<% else %>
	<h2>Для добавления комментария необходимо <%= link_to "войти/зарегистрироваться", signin_path %></h2>
<% end %>