config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :comments
    resources :users
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments
  resources :relationships, only: [:create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/search', to: 'articles#search', via: 'get'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Сыктывкар, 2015 год
  </small>
  <nav>
    <ul>
      <li><a href="http://vk.com/zidaneus">Создатель блога</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Тест блог", root_path, id: "logo" %>
      <nav>
        <ul class="nav nav-pills">
          <li><%= link_to "Статьи", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to 'Новая статья', new_article_path %></li>
            <li><%= link_to "Пользователи", users_path %></li>
            <ul class="nav nav-pills nav-right">
              <li id="fio_header"><%= gravatar_for current_user %> <%= truncate(current_user.fio, :length => 25) %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Профиль <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Мои статьи", current_user %></li>
                  <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Выйти", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            </ul>
          <% else %>
            <ul class="nav nav-pills nav-right">
              <li><%= link_to "Войти/зарегистрироваться", signin_path %></li>
            </ul>
          <% end %>
          <%= form_tag("/search", method: "get") do %>
            <li class="li_right_with_margin">  <%= submit_tag("Поиск") %> </li>
            <li class="li_right_with_margin">  <%= text_field_tag(:search) %> </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Тест блог</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>